name: Linters

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  lighthouse:
    name: Lighthouse
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Setup Lighthouse
        run: npm install -g @lhci/cli # Consider using the latest stable version
      - name: Lighthouse Report
        run: lhci autorun --upload.target=temporary-public-storage --collect.staticDistDir=.

  webhint:
    name: Webhint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Setup Webhint
        run: npm install --save-dev hint # Consider using the latest stable version
      - name: Webhint Report
        run: npx hint .

  stylelint:
    name: Stylelint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Setup Stylelint
        run: npm install --save-dev stylelint stylelint-scss stylelint-config-standard stylelint-csstree-validator # Consider using the latest stable versions
      - name: Stylelint Report
        run: npx stylelint "**/*.{css,scss}"

  nodechecker:
    name: node_modules checker
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check node_modules existence
        run: |
          if [ -d "node_modules/" ]; then
            echo -e "\e[1;31mError: The node_modules/ folder was pushed to the repo. Please remove it and ensure it's in your .gitignore file.\e[0m"
            exit 1
          fi